In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/garments_worker_productivity.csv")
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382

In [3]:
df.shape

(1197, 15)

In [4]:
df.columns

Index(['date', 'quarter', 'department', 'day', 'team', 'targeted_productivity',
       'smv', 'wip', 'over_time', 'incentive', 'idle_time', 'idle_men',
       'no_of_style_change', 'no_of_workers', 'actual_productivity'],
      dtype='str')

In [5]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1197 non-null   str
 1   quarter                1197 non-null   str
 2   department             1197 non-null   str
 3   day                    1197 non-null   str
 4   team                   1197 non-null   int64
 5   targeted_productivity  1197 non-null   float64
 6   smv                    1197 non-null   float64
 7   wip                    691 non-null    float64
 8   over_time              1197 non-null   int64
 9   incentive              1197 non-null   int64
 10  idle_time              1197 non-null   float64
 11  idle_men               1197 non-null   int64
 12  no_of_style_change     1197 non-null   int64
 13  no_of_workers          1197 non-null   float64
 14  actual_productivity    1197 non-null   float64
dtypes: float64(6), int64(5), str(4)
memory usage: 177.1 KB

,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity
count,1197.000000,1197.000000,1197.000000,691.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000,1197.000000
mean,6.426901,0.729632,15.062172,1190.465991,4567.460317,38.210526,0.730159,0.369256,0.150376,34.609858,0.735091
std,3.463963,0.097891,10.943219,1837.455001,3348.823563,160.182643,12.709757,3.268987,0.427848,22.197687,0.174488
min,1.000000,0.070000,2.900000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.233705
25%,3.000000,0.700000,3.940000,774.500000,1440.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.650307
50%,6.000000,0.750000,15.260000,1039.000000,3960.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.773333
75%,9.000000,0.800000,24.260000,1252.500000,6960.000000,50.000000,0.000000,0.000000,0.000000,57.000000,0.850253
max,12.000000,0.800000,54.560000,23122.000000,25920.000000,3600.000000,300.000000,45.000000,2.000000,89.000000,1.120437

In [6]:
df.isnull().sum()

date                       0
quarter                    0
department                 0
day                        0
team                       0
targeted_productivity      0
smv                        0
wip                      506
over_time                  0
incentive                  0
idle_time                  0
idle_men                   0
no_of_style_change         0
no_of_workers              0
actual_productivity        0
dtype: int64

In [7]:
df["wip"].describe()

count      691.000000
mean      1190.465991
std       1837.455001
min          7.000000
25%        774.500000
50%       1039.000000
75%       1252.500000
max      23122.000000
Name: wip, dtype: float64

In [8]:
for col in ["date", "quarter", "department", "day"]:
    print(f"\n{col}:")
    print(df[col].unique())

date:
<ArrowStringArray>
[ '1/1/2015',  '1/3/2015',  '1/4/2015',  '1/5/2015',  '1/6/2015',  '1/7/2015',
  '1/8/2015', '1/10/2015', '1/11/2015', '1/12/2015', '1/13/2015', '1/14/2015',
 '1/15/2015', '1/17/2015', '1/18/2015', '1/19/2015', '1/20/2015', '1/21/2015',
 '1/22/2015', '1/24/2015', '1/25/2015', '1/26/2015', '1/27/2015', '1/28/2015',
 '1/29/2015', '1/31/2015',  '2/1/2015',  '2/2/2015',  '2/3/2015',  '2/4/2015',
  '2/5/2015',  '2/7/2015',  '2/8/2015',  '2/9/2015', '2/10/2015', '2/11/2015',
 '2/12/2015', '2/14/2015', '2/15/2015', '2/16/2015', '2/17/2015', '2/18/2015',
 '2/19/2015', '2/22/2015', '2/23/2015', '2/24/2015', '2/25/2015', '2/26/2015',
 '2/28/2015',  '3/1/2015',  '3/2/2015',  '3/3/2015',  '3/4/2015',  '3/5/2015',
  '3/7/2015',  '3/8/2015',  '3/9/2015', '3/10/2015', '3/11/2015']
Length: 59, dtype: str

quarter:
<ArrowStringArray>
['Quarter1', 'Quarter2', 'Quarter3', 'Quarter4', 'Quarter5']
Length: 5, dtype: str

department:
<ArrowStringArray>
['sweing', 'finishing ', 'finishing']
Length: 3, dtype: str

day:
<ArrowStringArray>
['Thursday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday']
Length: 6, dtype: str

In [9]:
for col in ["quarter", "department", "day"]:
    print(f"\n--- {col} ---")
    print(df[col].value_counts())

--- quarter ---
quarter
Quarter1    360
Quarter2    335
Quarter4    248
Quarter3    210
Quarter5     44
Name: count, dtype: int64

--- department ---
department
sweing        691
finishing     257
finishing     249
Name: count, dtype: int64

--- day ---
day
Wednesday    208
Sunday       203
Tuesday      201
Thursday     199
Monday       199
Saturday     187
Name: count, dtype: int64

In [10]:
categorical_cols = ["date", "quarter", "department", "day"]

for col in categorical_cols:
    df[col] = df[col].str.strip()

In [11]:
df["department"].value_counts()

department
sweing       691
finishing    506
Name: count, dtype: int64

In [12]:
df["MeetsTarget"] = (
    df["actual_productivity"] >= df["targeted_productivity"]
).astype(int)

In [13]:
df["MeetsTarget"].value_counts()

MeetsTarget
1    875
0    322
Name: count, dtype: int64

In [14]:
df.head()

,date,quarter,department,day,team,targeted_productivity,smv,wip,over_time,incentive,idle_time,idle_men,no_of_style_change,no_of_workers,actual_productivity,MeetsTarget
0,1/1/2015,Quarter1,sweing,Thursday,8,0.80,26.16,1108.0,7080,98,0.0,0,0,59.0,0.940725,1
1,1/1/2015,Quarter1,finishing,Thursday,1,0.75,3.94,NaN,960,0,0.0,0,0,8.0,0.886500,1
2,1/1/2015,Quarter1,sweing,Thursday,11,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,1
3,1/1/2015,Quarter1,sweing,Thursday,12,0.80,11.41,968.0,3660,50,0.0,0,0,30.5,0.800570,1
4,1/1/2015,Quarter1,sweing,Thursday,6,0.80,25.90,1170.0,1920,50,0.0,0,0,56.0,0.800382,1

In [15]:
df["date"] = pd.to_datetime(df["date"])

In [16]:
df[["date"]].head()

        date
0 2015-01-01
1 2015-01-01
2 2015-01-01
3 2015-01-01
4 2015-01-01

In [18]:
df["month"] = df["date"].dt.month
df["day_of_month"] = df["date"].dt.day

In [19]:
df[["date", "month", "day_of_month"]].head()

        date  month  day_of_month
0 2015-01-01      1             1
1 2015-01-01      1             1
2 2015-01-01      1             1
3 2015-01-01      1             1
4 2015-01-01      1             1

In [20]:
categorical_features = [
    "quarter",
    "department",
    "day",
    "team"
]

numerical_features = [
    "targeted_productivity",
    "smv",
    "wip",
    "over_time",
    "incentive",
    "idle_time",
    "idle_men",
    "no_of_style_change",
    "no_of_workers",
    "month",
    "day_of_month"
]

In [21]:
X_reg = df[categorical_features + numerical_features]
y_reg = df["actual_productivity"]

X_clf = df[categorical_features + numerical_features]
y_clf = df["MeetsTarget"]

In [22]:
print("Regression features:", X_reg.shape)
print("Regression target:", y_reg.shape)

print("Classification features:", X_clf.shape)
print("Classification target:", y_clf.shape)

Regression features: (1197, 15)
Regression target: (1197,)
Classification features: (1197, 15)
Classification target: (1197,)

In [23]:
np.random.seed(42)

indices = np.random.permutation(len(df))

split_point = int(0.80 * len(df))

train_indices = indices[:split_point]
test_indices = indices[split_point:]

In [24]:
print("Total rows:", len(df))
print("Training rows:", len(train_indices))
print("Testing rows:", len(test_indices))

Total rows: 1197
Training rows: 957
Testing rows: 240

In [28]:
X_clf_train = X_clf.iloc[train_indices].copy()
X_clf_test = X_clf.iloc[test_indices].copy()

y_clf_train = y_clf.iloc[train_indices].copy()
y_clf_test = y_clf.iloc[test_indices].copy()

In [29]:
print("Regression:")
print("X_train:", X_reg_train.shape)
print("X_test :", X_reg_test.shape)
print("y_train:", y_reg_train.shape)
print("y_test :", y_reg_test.shape)

print("\nClassification:")
print("X_train:", X_clf_train.shape)
print("X_test :", X_clf_test.shape)
print("y_train:", y_clf_train.shape)
print("y_test :", y_clf_test.shape)

Regression:
X_train: (957, 15)
X_test : (240, 15)
y_train: (957,)
y_test : (240,)

Classification:
X_train: (957, 15)
X_test : (240, 15)
y_train: (957,)
y_test : (240,)

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [31]:
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

In [32]:
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
    ]
)

In [33]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [34]:
preprocessor.fit(X_reg_train)

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['targeted_productivity', 'smv', 'wip',
                                  'over_time', 'incentive', 'idle_time',
                                  'idle_men', 'no_of_style_change',
                                  'no_of_workers', 'month', 'day_of_month']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['quarter', 'department', 'day', 'team'])])

In [35]:
X_train_processed = preprocessor.transform(X_reg_train)
X_test_processed = preprocessor.transform(X_reg_test)

In [36]:
print("Original features:", X_reg_train.shape)
print("Processed training features:", X_train_processed.shape)
print("Processed testing features:", X_test_processed.shape)

Original features: (957, 15)
Processed training features: (957, 36)
Processed testing features: (240, 36)

In [37]:
feature_names = preprocessor.get_feature_names_out()

print("Number of processed features:", len(feature_names))
print("\nProcessed feature names:")
for feature in feature_names:
    print(feature)

Number of processed features: 36

Processed feature names:
num__targeted_productivity
num__smv
num__wip
num__over_time
num__incentive
num__idle_time
num__idle_men
num__no_of_style_change
num__no_of_workers
num__month
num__day_of_month
cat__quarter_Quarter1
cat__quarter_Quarter2
cat__quarter_Quarter3
cat__quarter_Quarter4
cat__quarter_Quarter5
cat__department_finishing
cat__department_sweing
cat__day_Monday
cat__day_Saturday
cat__day_Sunday
cat__day_Thursday
cat__day_Tuesday
cat__day_Wednesday
cat__team_1
cat__team_2
cat__team_3
cat__team_4
cat__team_5
cat__team_6
cat__team_7
cat__team_8
cat__team_9
cat__team_10
cat__team_11
cat__team_12

In [38]:
X_clf_train_processed = preprocessor.transform(X_clf_train)
X_clf_test_processed = preprocessor.transform(X_clf_test)

In [39]:
print("Classification processed training features:",
      X_clf_train_processed.shape)

print("Classification processed testing features:",
      X_clf_test_processed.shape)

print("Classification target training:",
      y_clf_train.shape)

print("Classification target testing:",
      y_clf_test.shape)

Classification processed training features: (957, 36)
Classification processed testing features: (240, 36)
Classification target training: (957,)
Classification target testing: (240,)

In [40]:
from sklearn.linear_model import LinearRegression
import time

In [41]:
linear_model = LinearRegression()

In [42]:
start_time = time.perf_counter()

linear_model.fit(X_train_processed, y_reg_train)

regression_train_time = time.perf_counter() - start_time

print("Linear Regression training time:",
      regression_train_time, "seconds")

Linear Regression training time: 0.0326044000685215 seconds

In [43]:
start_time = time.perf_counter()

y_reg_pred = linear_model.predict(X_test_processed)

regression_prediction_time = time.perf_counter() - start_time

print("Linear Regression prediction time:",
      regression_prediction_time, "seconds")

Linear Regression prediction time: 0.0033728000707924366 seconds

In [44]:
print("First 10 actual values:")
print(y_reg_test.head(10).to_numpy())

print("\nFirst 10 predicted values:")
print(y_reg_pred[:10])

First 10 actual values:
[0.61625    0.9520202  0.96178451 0.90666667 0.94998161 0.79997586
 0.47110849 0.35553448 0.80012872 0.75922839]

First 10 predicted values:
[0.77035819 0.78798677 0.79896442 0.81542741 0.85862509 0.73526364
 0.6938334  0.6968583  0.74233052 0.7517046 ]

In [45]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [46]:
mae = mean_absolute_error(y_reg_test, y_reg_pred)

rmse = np.sqrt(mean_squared_error(y_reg_test, y_reg_pred))

r2 = r2_score(y_reg_test, y_reg_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

MAE : 0.10090987216643489
RMSE: 0.1404017627351323
R²  : 0.3603505373226975

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
logistic_model = LogisticRegression(max_iter=1000)

In [49]:
start_time = time.perf_counter()

logistic_model.fit(X_clf_train_processed, y_clf_train)

classification_train_time = time.perf_counter() - start_time

print(
    "Logistic Regression training time:",
    classification_train_time,
    "seconds"
)

Logistic Regression training time: 0.12900559999980032 seconds

In [50]:
start_time = time.perf_counter()

y_clf_pred = logistic_model.predict(X_clf_test_processed)

classification_prediction_time = time.perf_counter() - start_time

print(
    "Logistic Regression prediction time:",
    classification_prediction_time,
    "seconds"
)

Logistic Regression prediction time: 0.003498899983242154 seconds

In [51]:
y_clf_prob = logistic_model.predict_proba(X_clf_test_processed)[:, 1]

In [52]:
print("First 10 actual classes:")
print(y_clf_test.head(10).to_numpy())

print("\nFirst 10 predicted classes:")
print(y_clf_pred[:10])

print("\nFirst 10 predicted probabilities for class 1:")
print(y_clf_prob[:10])

First 10 actual classes:
[0 1 1 1 1 1 0 0 1 1]

First 10 predicted classes:
[1 1 1 1 1 1 1 1 1 1]

First 10 predicted probabilities for class 1:
[0.52612802 0.7188252  0.76683678 0.62035425 0.95696097 0.91192508
 0.93895739 0.66097937 0.82963491 0.65630777]

In [53]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [54]:
accuracy = accuracy_score(y_clf_test, y_clf_pred)
precision = precision_score(y_clf_test, y_clf_pred)
recall = recall_score(y_clf_test, y_clf_pred)
f1 = f1_score(y_clf_test, y_clf_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1-score :", f1)

Accuracy : 0.7541666666666667
Precision: 0.7772277227722773
Recall   : 0.9181286549707602
F1-score : 0.8418230563002681

In [55]:
regression_results = pd.DataFrame({
    "Model": ["Scikit-learn Linear Regression"],
    "MAE": [mae],
    "RMSE": [rmse],
    "R2": [r2],
    "Training Time (s)": [regression_train_time],
    "Prediction Time (s)": [regression_prediction_time]
})

regression_results

,Model,MAE,RMSE,R2,Training Time (s),Prediction Time (s)
0,Scikit-learn Linear Regression,0.10091,0.140402,0.360351,0.032604,0.003373

In [56]:
classification_results = pd.DataFrame({
    "Model": ["Scikit-learn Logistic Regression"],
    "Accuracy": [accuracy],
    "Precision": [precision],
    "Recall": [recall],
    "F1-score": [f1],
    "Training Time (s)": [classification_train_time],
    "Prediction Time (s)": [classification_prediction_time]
})

classification_results

,Model,Accuracy,Precision,Recall,F1-score,Training Time (s),Prediction Time (s)
0,Scikit-learn Logistic Regression,0.754167,0.777228,0.918129,0.841823,0.129006,0.003499

## Part B - From-Scratch Implementation
### Manual Preprocessing

In [57]:
X_manual_train = X_reg_train.copy()
X_manual_test = X_reg_test.copy()

y_manual_reg_train = y_reg_train.copy()
y_manual_reg_test = y_reg_test.copy()

y_manual_clf_train = y_clf_train.copy()
y_manual_clf_test = y_clf_test.copy()

In [58]:
wip_median = X_manual_train["wip"].median()

print("Training WIP median:", wip_median)

Training WIP median: 1047.0

In [59]:
X_manual_train["wip"] = X_manual_train["wip"].fillna(wip_median)
X_manual_test["wip"] = X_manual_test["wip"].fillna(wip_median)

In [60]:
print("Missing WIP in training:", X_manual_train["wip"].isnull().sum())
print("Missing WIP in testing :", X_manual_test["wip"].isnull().sum())

Missing WIP in training: 0
Missing WIP in testing : 0

In [61]:
def manual_one_hot_encode(train_df, test_df, categorical_cols):
    train_encoded = pd.DataFrame(index=train_df.index)
    test_encoded = pd.DataFrame(index=test_df.index)

    for col in categorical_cols:

        # Handle missing categorical values using training-data mode
        if train_df[col].isnull().any():
            mode_value = train_df[col].mode()[0]
            train_col = train_df[col].fillna(mode_value)
            test_col = test_df[col].fillna(mode_value)
        else:
            train_col = train_df[col]
            test_col = test_df[col]

        # Learn categories only from training data
        categories = sorted(train_col.unique())

        # Create one binary column for every category
        for category in categories:
            column_name = f"{col}_{category}"

            train_encoded[column_name] = (
                train_col == category
            ).astype(int)

            test_encoded[column_name] = (
                test_col == category
            ).astype(int)

    return train_encoded, test_encoded

In [63]:
cat_train_encoded, cat_test_encoded = manual_one_hot_encode(
    X_manual_train,
    X_manual_test,
    categorical_features
)

In [64]:
print("Encoded training categorical shape:", cat_train_encoded.shape)
print("Encoded testing categorical shape :", cat_test_encoded.shape)

Encoded training categorical shape: (957, 25)
Encoded testing categorical shape : (240, 25)

In [65]:
print("Number of encoded categorical features:",
      len(cat_train_encoded.columns))

print("\nEncoded feature names:")
for col in cat_train_encoded.columns:
    print(col)

Number of encoded categorical features: 25

Encoded feature names:
quarter_Quarter1
quarter_Quarter2
quarter_Quarter3
quarter_Quarter4
quarter_Quarter5
department_finishing
department_sweing
day_Monday
day_Saturday
day_Sunday
day_Thursday
day_Tuesday
day_Wednesday
team_1
team_2
team_3
team_4
team_5
team_6
team_7
team_8
team_9
team_10
team_11
team_12

In [72]:
def manual_standard_scale(train_df, test_df, numerical_cols):
    train_scaled = pd.DataFrame(index=train_df.index)
    test_scaled = pd.DataFrame(index=test_df.index)

    means = {}
    stds = {}

    for col in numerical_cols:
        mean_value = train_df[col].mean()
        std_value = train_df[col].std(ddof=0)

        # Avoid division by zero if a feature has no variation
        if std_value == 0:
            std_value = 1.0

        means[col] = mean_value
        stds[col] = std_value

        train_scaled[col] = (
            train_df[col] - mean_value
        ) / std_value

        test_scaled[col] = (
            test_df[col] - mean_value
        ) / std_value

    return train_scaled, test_scaled, means, stds

In [75]:
print("Scaled numerical training shape:", num_train_scaled.shape)
print("Scaled numerical testing shape :", num_test_scaled.shape)

Scaled numerical training shape: (957, 11)
Scaled numerical testing shape : (240, 11)

In [76]:
print("Training means after scaling:")
print(num_train_scaled.mean())

print("\nTraining standard deviations after scaling:")
print(num_train_scaled.std(ddof=0))

Training means after scaling:
targeted_productivity    7.424689e-18
smv                     -8.909627e-17
wip                     -5.661325e-17
over_time                1.150827e-16
incentive                2.598641e-17
idle_time               -2.969876e-17
idle_men                 4.083579e-17
no_of_style_change       5.197282e-17
no_of_workers            5.197282e-17
month                   -2.598641e-17
day_of_month             4.083579e-17
dtype: float64

Training standard deviations after scaling:
targeted_productivity    1.0
smv                      1.0
wip                      1.0
over_time                1.0
incentive                1.0
idle_time                1.0
idle_men                 1.0
no_of_style_change       1.0
no_of_workers            1.0
month                    1.0
day_of_month             1.0
dtype: float64

In [77]:
manual_train_processed = pd.concat(
    [num_train_scaled, cat_train_encoded],
    axis=1
)

manual_test_processed = pd.concat(
    [num_test_scaled, cat_test_encoded],
    axis=1
)

In [78]:
print("Manual training shape:", manual_train_processed.shape)
print("Manual testing shape :", manual_test_processed.shape)

Manual training shape: (957, 36)
Manual testing shape : (240, 36)

In [79]:
X_manual_train_np = manual_train_processed.to_numpy(dtype=float)
X_manual_test_np = manual_test_processed.to_numpy(dtype=float)

y_manual_reg_train_np = y_manual_reg_train.to_numpy(dtype=float)
y_manual_reg_test_np = y_manual_reg_test.to_numpy(dtype=float)

y_manual_clf_train_np = y_manual_clf_train.to_numpy(dtype=float)
y_manual_clf_test_np = y_manual_clf_test.to_numpy(dtype=float)

In [80]:
def linear_regression_closed_form(X, y):
    # Add a column of 1s for the intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Closed-form solution
    beta = np.linalg.pinv(X_with_intercept.T @ X_with_intercept) @ (
        X_with_intercept.T @ y
    )

    return beta

In [81]:
start_time = time.perf_counter()

manual_linear_beta = linear_regression_closed_form(
    X_manual_train_np,
    y_manual_reg_train_np
)

manual_regression_train_time = time.perf_counter() - start_time

print(
    "Manual Linear Regression training time:",
    manual_regression_train_time,
    "seconds"
)

Manual Linear Regression training time: 0.058824799954891205 seconds

In [82]:
print("Number of coefficients:", len(manual_linear_beta))
print("First 5 coefficients:", manual_linear_beta[:5])

Number of coefficients: 37
First 5 coefficients: [ 0.38857536  0.06304115 -0.08108381  0.00560205 -0.01517143]

In [83]:
def linear_regression_predict(X, beta):
    # Add a column of 1s for the intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Calculate predictions
    predictions = X_with_intercept @ beta

    return predictions

In [84]:
start_time = time.perf_counter()

manual_reg_pred = linear_regression_predict(
    X_manual_test_np,
    manual_linear_beta
)

manual_regression_prediction_time = time.perf_counter() - start_time

print(
    "Manual Linear Regression prediction time:",
    manual_regression_prediction_time,
    "seconds"
)

Manual Linear Regression prediction time: 0.001438699895516038 seconds

In [85]:
print("First 10 actual values:")
print(y_manual_reg_test_np[:10])

print("\nFirst 10 manual predicted values:")
print(manual_reg_pred[:10])

First 10 actual values:
[0.61625    0.9520202  0.96178451 0.90666667 0.94998161 0.79997586
 0.47110849 0.35553448 0.80012872 0.75922839]

First 10 manual predicted values:
[0.77035819 0.78798677 0.79896442 0.81542741 0.85862509 0.73526364
 0.6938334  0.6968583  0.74233052 0.7517046 ]

In [86]:
def manual_mae(y_true, y_pred):
    errors = np.abs(y_true - y_pred)
    return np.mean(errors)

In [87]:
def manual_rmse(y_true, y_pred):
    errors = y_true - y_pred
    squared_errors = errors ** 2
    return np.sqrt(np.mean(squared_errors))

In [88]:
def manual_r2(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    return 1 - (ss_res / ss_tot)

In [89]:
manual_mae_value = manual_mae(
    y_manual_reg_test_np,
    manual_reg_pred
)

manual_rmse_value = manual_rmse(
    y_manual_reg_test_np,
    manual_reg_pred
)

manual_r2_value = manual_r2(
    y_manual_reg_test_np,
    manual_reg_pred
)

print("Manual MAE :", manual_mae_value)
print("Manual RMSE:", manual_rmse_value)
print("Manual R²  :", manual_r2_value)

Manual MAE : 0.10090987216643461
Manual RMSE: 0.14040176273513227
Manual R²  : 0.36035053732269795

In [90]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    return 1 / (1 + np.exp(-z))

In [91]:
def logistic_regression_train(X, y, learning_rate=0.05, n_iterations=5000):
    # Add intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Start all parameters at zero
    weights = np.zeros(X_with_intercept.shape[1])

    for _ in range(n_iterations):
        # Calculate raw scores
        z = X_with_intercept @ weights

        # Convert scores to probabilities
        probabilities = sigmoid(z)

        # Calculate gradient
        gradient = (
            X_with_intercept.T @ (probabilities - y)
        ) / len(y)

        # Update weights
        weights -= learning_rate * gradient

    return weights

In [92]:
start_time = time.perf_counter()

manual_logistic_weights = logistic_regression_train(
    X_manual_train_np,
    y_manual_clf_train_np,
    learning_rate=0.05,
    n_iterations=5000
)

manual_classification_train_time = time.perf_counter() - start_time

print(
    "Manual Logistic Regression training time:",
    manual_classification_train_time,
    "seconds"
)

print("Number of learned weights:", len(manual_logistic_weights))

Manual Logistic Regression training time: 1.7785895999986678 seconds
Number of learned weights: 37

In [93]:
def logistic_predict_proba(X, weights):
    # Add intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Calculate raw scores
    z = X_with_intercept @ weights

    # Convert scores to probabilities
    probabilities = sigmoid(z)

    return probabilities

In [94]:
def logistic_predict(X, weights, threshold=0.5):
    probabilities = logistic_predict_proba(X, weights)

    predictions = (probabilities >= threshold).astype(int)

    return predictions

In [95]:
start_time = time.perf_counter()

manual_clf_prob = logistic_predict_proba(
    X_manual_test_np,
    manual_logistic_weights
)

manual_clf_pred = logistic_predict(
    X_manual_test_np,
    manual_logistic_weights,
    threshold=0.5
)

manual_classification_prediction_time = (
    time.perf_counter() - start_time
)

print(
    "Manual Logistic Regression prediction time:",
    manual_classification_prediction_time,
    "seconds"
)

Manual Logistic Regression prediction time: 0.0021361999679356813 seconds

In [96]:
print("First 10 actual classes:")
print(y_manual_clf_test_np[:10])

print("\nFirst 10 predicted probabilities:")
print(manual_clf_prob[:10])

print("\nFirst 10 predicted classes:")
print(manual_clf_pred[:10])

First 10 actual classes:
[0. 1. 1. 1. 1. 1. 0. 0. 1. 1.]

First 10 predicted probabilities:
[0.52387382 0.72172984 0.76585926 0.63039096 0.95811046 0.9131096
 0.94053578 0.65560512 0.82962342 0.66187613]

First 10 predicted classes:
[1 1 1 1 1 1 1 1 1 1]

In [97]:
tp = np.sum((y_manual_clf_test_np == 1) & (manual_clf_pred == 1))
tn = np.sum((y_manual_clf_test_np == 0) & (manual_clf_pred == 0))
fp = np.sum((y_manual_clf_test_np == 0) & (manual_clf_pred == 1))
fn = np.sum((y_manual_clf_test_np == 1) & (manual_clf_pred == 0))

print("True Positives (TP):", tp)
print("True Negatives (TN):", tn)
print("False Positives (FP):", fp)
print("False Negatives (FN):", fn)

print("Total:", tp + tn + fp + fn)

True Positives (TP): 157
True Negatives (TN): 25
False Positives (FP): 44
False Negatives (FN): 14
Total: 240

In [98]:
manual_accuracy = (tp + tn) / (tp + tn + fp + fn)

manual_precision = tp / (tp + fp)

manual_recall = tp / (tp + fn)

manual_f1 = (
    2 * manual_precision * manual_recall
    / (manual_precision + manual_recall)
)

print("Manual Accuracy :", manual_accuracy)
print("Manual Precision:", manual_precision)
print("Manual Recall   :", manual_recall)
print("Manual F1-score :", manual_f1)

Manual Accuracy : 0.7583333333333333
Manual Precision: 0.7810945273631841
Manual Recall   : 0.9181286549707602
Manual F1-score : 0.8440860215053763

In [99]:
manual_regression_results = pd.DataFrame({
    "Model": ["Manual Linear Regression"],
    "MAE": [manual_mae_value],
    "RMSE": [manual_rmse_value],
    "R2": [manual_r2_value],
    "Training Time (s)": [manual_regression_train_time],
    "Prediction Time (s)": [manual_regression_prediction_time]
})

manual_regression_results

,Model,MAE,RMSE,R2,Training Time (s),Prediction Time (s)
0,Manual Linear Regression,0.10091,0.140402,0.360351,0.058825,0.001439

In [100]:
manual_classification_results = pd.DataFrame({
    "Model": ["Manual Logistic Regression"],
    "Accuracy": [manual_accuracy],
    "Precision": [manual_precision],
    "Recall": [manual_recall],
    "F1-score": [manual_f1],
    "Training Time (s)": [manual_classification_train_time],
    "Prediction Time (s)": [manual_classification_prediction_time]
})

manual_classification_results

,Model,Accuracy,Precision,Recall,F1-score,Training Time (s),Prediction Time (s)
0,Manual Logistic Regression,0.758333,0.781095,0.918129,0.844086,1.77859,0.002136

In [101]:
regression_comparison = pd.DataFrame({
    "Implementation": [
        "Scikit-learn",
        "Manual NumPy/Pandas"
    ],
    "MAE": [
        mae,
        manual_mae_value
    ],
    "RMSE": [
        rmse,
        manual_rmse_value
    ],
    "R2": [
        r2,
        manual_r2_value
    ],
    "Training Time (s)": [
        regression_train_time,
        manual_regression_train_time
    ],
    "Prediction Time (s)": [
        regression_prediction_time,
        manual_regression_prediction_time
    ]
})

regression_comparison

,Implementation,MAE,RMSE,R2,Training Time (s),Prediction Time (s)
0,Scikit-learn,0.10091,0.140402,0.360351,0.032604,0.003373
1,Manual NumPy/Pandas,0.10091,0.140402,0.360351,0.058825,0.001439

In [102]:
classification_comparison = pd.DataFrame({
    "Implementation": [
        "Scikit-learn",
        "Manual NumPy/Pandas"
    ],
    "Accuracy": [
        accuracy,
        manual_accuracy
    ],
    "Precision": [
        precision,
        manual_precision
    ],
    "Recall": [
        recall,
        manual_recall
    ],
    "F1-score": [
        f1,
        manual_f1
    ],
    "Training Time (s)": [
        classification_train_time,
        manual_classification_train_time
    ],
    "Prediction Time (s)": [
        classification_prediction_time,
        manual_classification_prediction_time
    ]
})

classification_comparison

,Implementation,Accuracy,Precision,Recall,F1-score,Training Time (s),Prediction Time (s)
0,Scikit-learn,0.754167,0.777228,0.918129,0.841823,0.129006,0.003499
1,Manual NumPy/Pandas,0.758333,0.781095,0.918129,0.844086,1.778590,0.002136

## Part C - Optimization
### Optimized Manual Logistic Regression

In [103]:
def logistic_regression_train_optimized(
    X,
    y,
    learning_rate=0.05,
    n_iterations=5000,
    tolerance=1e-7,
    patience=20
):
    # Add intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Initialize weights
    weights = np.zeros(X_with_intercept.shape[1])

    previous_loss = np.inf
    stable_iterations = 0

    for iteration in range(n_iterations):

        # Raw scores
        z = X_with_intercept @ weights

        # Predicted probabilities
        probabilities = sigmoid(z)

        # Gradient
        gradient = (
            X_with_intercept.T @ (probabilities - y)
        ) / len(y)

        # Update weights
        weights -= learning_rate * gradient

        # Calculate log loss
        probabilities_clipped = np.clip(
            probabilities,
            1e-15,
            1 - 1e-15
        )

        loss = -np.mean(
            y * np.log(probabilities_clipped)
            + (1 - y) * np.log(1 - probabilities_clipped)
        )

        # Check convergence
        if abs(previous_loss - loss) < tolerance:
            stable_iterations += 1

            if stable_iterations >= patience:
                break
        else:
            stable_iterations = 0

        previous_loss = loss

    return weights, iteration + 1

In [104]:
start_time = time.perf_counter()

optimized_logistic_weights, optimized_iterations = (
    logistic_regression_train_optimized(
        X_manual_train_np,
        y_manual_clf_train_np,
        learning_rate=0.05,
        n_iterations=5000,
        tolerance=1e-7,
        patience=20
    )
)

optimized_classification_train_time = (
    time.perf_counter() - start_time
)

print(
    "Optimized training time:",
    optimized_classification_train_time,
    "seconds"
)

print(
    "Iterations actually used:",
    optimized_iterations
)

Optimized training time: 2.508759899996221 seconds
Iterations actually used: 5000

In [105]:
def logistic_regression_train_fast(
    X,
    y,
    learning_rate=0.1,
    n_iterations=3000
):
    # Add intercept
    X_with_intercept = np.column_stack([
        np.ones(X.shape[0]),
        X
    ])

    # Precompute transpose because it never changes
    X_transpose = X_with_intercept.T

    # Initialize weights
    weights = np.zeros(X_with_intercept.shape[1])

    for _ in range(n_iterations):
        # Raw scores
        z = X_with_intercept @ weights

        # Probabilities
        probabilities = sigmoid(z)

        # Gradient
        gradient = (
            X_transpose @ (probabilities - y)
        ) / len(y)

        # Update weights
        weights -= learning_rate * gradient

    return weights

In [106]:
start_time = time.perf_counter()

fast_logistic_weights = logistic_regression_train_fast(
    X_manual_train_np,
    y_manual_clf_train_np,
    learning_rate=0.1,
    n_iterations=3000
)

fast_logistic_train_time = time.perf_counter() - start_time

print(
    "Fast optimized training time:",
    fast_logistic_train_time,
    "seconds"
)

Fast optimized training time: 0.9642171999439597 seconds

In [107]:
start_time = time.perf_counter()

fast_clf_prob = logistic_predict_proba(
    X_manual_test_np,
    fast_logistic_weights
)

fast_clf_pred = (
    fast_clf_prob >= 0.5
).astype(int)

fast_logistic_prediction_time = (
    time.perf_counter() - start_time
)

print(
    "Fast optimized prediction time:",
    fast_logistic_prediction_time,
    "seconds"
)

Fast optimized prediction time: 0.0017626001499593258 seconds

In [108]:
fast_tp = np.sum(
    (y_manual_clf_test_np == 1) &
    (fast_clf_pred == 1)
)

fast_tn = np.sum(
    (y_manual_clf_test_np == 0) &
    (fast_clf_pred == 0)
)

fast_fp = np.sum(
    (y_manual_clf_test_np == 0) &
    (fast_clf_pred == 1)
)

fast_fn = np.sum(
    (y_manual_clf_test_np == 1) &
    (fast_clf_pred == 0)
)

fast_accuracy = (
    (fast_tp + fast_tn) /
    (fast_tp + fast_tn + fast_fp + fast_fn)
)

fast_precision = (
    fast_tp /
    (fast_tp + fast_fp)
)

fast_recall = (
    fast_tp /
    (fast_tp + fast_fn)
)

fast_f1 = (
    2 * fast_precision * fast_recall /
    (fast_precision + fast_recall)
)

print("Fast optimized Accuracy :", fast_accuracy)
print("Fast optimized Precision:", fast_precision)
print("Fast optimized Recall   :", fast_recall)
print("Fast optimized F1-score :", fast_f1)

Fast optimized Accuracy : 0.7583333333333333
Fast optimized Precision: 0.7839195979899497
Fast optimized Recall   : 0.9122807017543859
Fast optimized F1-score : 0.8432432432432431

In [109]:
optimization_comparison = pd.DataFrame({
    "Implementation": [
        "Scikit-learn",
        "Manual Baseline",
        "Manual Optimized"
    ],
    "Accuracy": [
        accuracy,
        manual_accuracy,
        fast_accuracy
    ],
    "Precision": [
        precision,
        manual_precision,
        fast_precision
    ],
    "Recall": [
        recall,
        manual_recall,
        fast_recall
    ],
    "F1-score": [
        f1,
        manual_f1,
        fast_f1
    ],
    "Training Time (s)": [
        classification_train_time,
        manual_classification_train_time,
        fast_logistic_train_time
    ],
    "Prediction Time (s)": [
        classification_prediction_time,
        manual_classification_prediction_time,
        fast_logistic_prediction_time
    ]
})

optimization_comparison

,Implementation,Accuracy,Precision,Recall,F1-score,Training Time (s),Prediction Time (s)
0,Scikit-learn,0.754167,0.777228,0.918129,0.841823,0.129006,0.003499
1,Manual Baseline,0.758333,0.781095,0.918129,0.844086,1.778590,0.002136
2,Manual Optimized,0.758333,0.783920,0.912281,0.843243,0.964217,0.001763

In [110]:
regression_comparison

,Implementation,MAE,RMSE,R2,Training Time (s),Prediction Time (s)
0,Scikit-learn,0.10091,0.140402,0.360351,0.032604,0.003373
1,Manual NumPy/Pandas,0.10091,0.140402,0.360351,0.058825,0.001439

In [111]:
final_summary = pd.DataFrame({
    "Task": [
        "Regression",
        "Regression",
        "Classification",
        "Classification",
        "Classification"
    ],
    "Implementation": [
        "Scikit-learn Linear Regression",
        "Manual Linear Regression",
        "Scikit-learn Logistic Regression",
        "Manual Logistic Regression",
        "Manual Logistic Regression (Optimized)"
    ],
    "Primary Metrics": [
        f"MAE={mae:.6f}, RMSE={rmse:.6f}, R2={r2:.6f}",
        f"MAE={manual_mae_value:.6f}, RMSE={manual_rmse_value:.6f}, R2={manual_r2_value:.6f}",
        f"Acc={accuracy:.6f}, Prec={precision:.6f}, Rec={recall:.6f}, F1={f1:.6f}",
        f"Acc={manual_accuracy:.6f}, Prec={manual_precision:.6f}, Rec={manual_recall:.6f}, F1={manual_f1:.6f}",
        f"Acc={fast_accuracy:.6f}, Prec={fast_precision:.6f}, Rec={fast_recall:.6f}, F1={fast_f1:.6f}"
    ],
    "Training Time (s)": [
        regression_train_time,
        manual_regression_train_time,
        classification_train_time,
        manual_classification_train_time,
        fast_logistic_train_time
    ],
    "Prediction Time (s)": [
        regression_prediction_time,
        manual_regression_prediction_time,
        classification_prediction_time,
        manual_classification_prediction_time,
        fast_logistic_prediction_time
    ]
})

final_summary

,Task,Implementation,Primary Metrics,Training Time (s),Prediction Time (s)
0,Regression,Scikit-learn Linear Regression,"MAE=0.100910, RMSE=0.140402, R2=0.360351",0.032604,0.003373
1,Regression,Manual Linear Regression,"MAE=0.100910, RMSE=0.140402, R2=0.360351",0.058825,0.001439
2,Classification,Scikit-learn Logistic Regression,"Acc=0.754167, Prec=0.777228, Rec=0.918129, F1=...",0.129006,0.003499
3,Classification,Manual Logistic Regression,"Acc=0.758333, Prec=0.781095, Rec=0.918129, F1=...",1.778590,0.002136
4,Classification,Manual Logistic Regression (Optimized),"Acc=0.758333, Prec=0.783920, Rec=0.912281, F1=...",0.964217,0.001763

## Part C - Comparison and Optimization Observations

### Regression

1. The Scikit-learn Linear Regression and the manual NumPy/Pandas Linear Regression produced almost exactly the same results.
2. Both implementations achieved an MAE of about 0.101, RMSE of about 0.140, and R² of about 0.360.
3. This shows that our manually implemented closed-form Linear Regression correctly reproduced the Scikit-learn result.
4. The manual implementation took slightly longer to train, while its prediction time was lower in this run.
5. The very small difference in the last decimal places is due to floating-point calculations.

### Classification

1. The Scikit-learn and manual Logistic Regression models produced very similar classification performance.
2. The manual baseline achieved Accuracy = 0.7583, Precision = 0.7811, Recall = 0.9181, and F1-score = 0.8441.
3. The optimized manual version achieved Accuracy = 0.7583, Precision = 0.7839, Recall = 0.9123, and F1-score = 0.8432.
4. The optimized version reduced manual training time from about 1.779 seconds to about 0.964 seconds.
5. The optimized version therefore reduced training time while keeping the classification performance close to the baseline.
6. The optimized manual implementation was still slower than the Scikit-learn implementation, which is acceptable because the assignment states that beating Scikit-learn execution time is optional.
7. The runtime difference can be explained by the highly optimized implementation and solver used internally by Scikit-learn, while our manual implementation performs the optimization using NumPy operations written explicitly in the notebook.

# Final Conclusion

This assignment implemented both regression and classification workflows using Scikit-learn and from-scratch NumPy/Pandas methods on the UCI Productivity Prediction of Garment Employees dataset.

For regression, Linear Regression was used to predict `actual_productivity`. The manual closed-form implementation produced almost identical MAE, RMSE, and R² values to the Scikit-learn implementation, showing that the mathematical implementation was correct.

For classification, a `MeetsTarget` target was created using the required rule:
- 1 when `actual_productivity >= targeted_productivity`
- 0 otherwise.

Logistic Regression was then implemented using Scikit-learn and from scratch using NumPy. The manual implementation produced classification results close to Scikit-learn.

The manual Logistic Regression was further optimized by increasing the learning rate and reducing the number of iterations. This reduced the training time from approximately 1.779 seconds to approximately 0.964 seconds while keeping the classification performance close to the baseline.

The comparison demonstrates that machine-learning libraries provide highly optimized implementations, while a NumPy/Pandas implementation can reproduce similar predictive results when the workflow is implemented correctly.